[profile.release]
debug = true
codegen-units = 1

[workspace]
members = [
    "cdt",
    "express",
    "step",
    "gui",
    "nurbs",
    "triangulate",
]
exclude = [
    "wasm",
]

[workspace.dependencies]
gltf = "1.4.1"
